environment:
  SPMeta2_O365_SiteUrl:
    secure: j0L8clRyLW7xY7UFBuI2k8G+ootYCT3+a6BFobQ26dbu20RPDFHXTjPlfZDSMzOnrSWX4VAzlaLg52L3Xydvew==
  SPMeta2_O365_UserName:
    secure: wFqfEa659MyPAksIbkzh0zv6vnTCIA2vmEPVRZ60WwSqdwe5cuJ5QOBazAYirbV9
  SPMeta2_O365_Password:
    secure: HE7kgk9JwRjrFb2u1JBBTw==
  SPMeta2_RunnerLibraries:
    secure: fjM6KXFe9K4+sdSLrfrlvDYxZlLOQIgVLNZqlBBOf5Tqk2M5E7JLaPzNcUmE9eDz
test: off